In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from lightgbm import LGBMRegressor
import lightgbm as lgb

### preprocessing

In [2]:
# load files
sales = pd.read_csv("sales_train_validation.csv")
calendar = pd.read_csv("calendar.csv")
sell_prices = pd.read_csv("sell_prices.csv")

# convert date column to datetime
calendar["date"] = pd.to_datetime(calendar["date"])

# keep id columns separately
id_cols = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]
day_cols = [c for c in sales.columns if c.startswith("d_")]

# -----------------------------
# keep last 500 days BEFORE melt
# but only days that exist in sales
# -----------------------------
cutoff_date = calendar["date"].max() - pd.Timedelta(days=500)
calendar = calendar[calendar["date"] > cutoff_date].copy()

keep_day_cols = [d for d in calendar["d"].tolist() if d in sales.columns]
calendar = calendar[calendar["d"].isin(keep_day_cols)].copy()

sales = sales[id_cols + keep_day_cols]

# wide to long
sales_long = sales.melt(
    id_vars=id_cols,
    value_vars=keep_day_cols,
    var_name="d",
    value_name="sales"
)

# join calendar info
df = sales_long.merge(calendar, on="d", how="left")
del sales_long

# join prices using Walmart week key
df = df.merge(
    sell_prices,
    on=["store_id", "item_id", "wm_yr_wk"],
    how="left"
)

# date handling
df["date"] = pd.to_datetime(df["date"])

# reduce memory a bit
for col in df.select_dtypes(include=["int64"]).columns:
    df[col] = pd.to_numeric(df[col], downcast="integer")

for col in df.select_dtypes(include=["float64"]).columns:
    df[col] = pd.to_numeric(df[col], downcast="float")

# combine snap into single feature instead of state wise columns
df["snap"] = 0
df.loc[df["state_id"] == "CA", "snap"] = df["snap_CA"]
df.loc[df["state_id"] == "TX", "snap"] = df["snap_TX"]
df.loc[df["state_id"] == "WI", "snap"] = df["snap_WI"]

df = df.drop(columns=["snap_CA", "snap_TX", "snap_WI"])

# keep event type only
df = df.drop(columns=["event_name_1", "event_name_2"])

# use just event type 1
df["event_type"] = df["event_type_1"].fillna("None")
df = df.drop(columns=["event_type_1", "event_type_2"])

# keep categorical columns as category dtype
cat_cols = [
    "item_id", "dept_id", "cat_id", "store_id", "state_id",
    "weekday", "event_type"
]
for col in cat_cols:
    if col in df.columns:
        df[col] = df[col].astype("category")

df = df.drop(columns=["d"])

# sort before feature engineering
df = df.sort_values(["store_id", "item_id", "date"], ignore_index=True)

In [3]:
df.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'sales',
       'date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'sell_price',
       'snap', 'event_type'],
      dtype='object')

In [4]:
df.head(5)

,id,item_id,dept_id,cat_id,store_id,state_id,sales,date,wm_yr_wk,weekday,wday,month,year,sell_price,snap,event_type
0,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2015-02-06,11501,Friday,7,2,2015,2.24,1,None
1,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,0,2015-02-07,11502,Saturday,1,2,2015,2.24,1,None
2,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,2,2015-02-08,11502,Sunday,2,2,2015,2.24,1,None
3,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,1,2015-02-09,11502,Monday,3,2,2015,2.24,1,None
4,FOODS_1_001_CA_1_validation,FOODS_1_001,FOODS_1,FOODS,CA_1,CA,1,2015-02-10,11502,Tuesday,4,2,2015,2.24,1,None

### feature engineering

lag_7, lag_14, lag_28, lag_56: past sales values at fixed lags capturing weekly/monthly demand patterns.

rmean_7, rmean_14, rmean_28: rolling average of past sales capturing smoothed demand trends.

rstd_7, rstd_14, rstd_28: rolling standard deviation capturing demand volatility.

price_change: ratio of current price to previous price capturing price shocks.

price_mean_7: rolling average of past prices capturing pricing trends.

dayofweek: numeric day index capturing weekly seasonality.

month: month index capturing yearly seasonality.

weekofyear: week index capturing finer seasonal cycles.

is_weekend: binary flag capturing weekend demand effects.

store_sales_mean_7: rolling mean of total store demand capturing store-level trends.

cat_sales_mean_7: rolling mean of category demand capturing product-group trends.

In [5]:
# ensure sorted
df = df.sort_values(["store_id", "item_id", "date"])

# -------- LAG FEATURES --------
lags = [1, 7, 28]

for lag in lags:
    df[f"lag_{lag}"] = df.groupby(["store_id", "item_id"])["sales"].shift(lag)

# -------- ROLLING FEATURES --------
# not usnig any rolling std for now, likely noisy and not very helpful

g = df.groupby(["store_id", "item_id"])["sales"]

for window in [3, 7, 28]:
    df[f"rmean_{window}"] = (
        g.shift(1)
        .rolling(window)
        .mean()
    )




# -------- PRICE FEATURES --------
# price change (very important)
df["price_lag_1"] = df.groupby(["store_id", "item_id"])["sell_price"].shift(1)
df["price_change"] = df["sell_price"] / df["price_lag_1"]

# price momentum
df["price_mean_7"] = (
    df.groupby(["store_id", "item_id"])["sell_price"]
    .shift(1)
    .rolling(7)
    .mean()
)

# -------- CALENDAR FEATURES --------
df["dayofweek"] = df["date"].dt.dayofweek
df["month"] = df["date"].dt.month
df["weekofyear"] = df["date"].dt.isocalendar().week.astype("int")

# weekend flag
df["is_weekend"] = (df["dayofweek"] >= 5).astype(int)

# SNAP already exists → keep as is

# -------- HIERARCHICAL FEATURES (IMPORTANT BOOST) --------

# store-level demand
df["store_sales_mean_7"] = (
    df.groupby(["store_id", "date"])["sales"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

# category-level demand
df["cat_sales_mean_7"] = (
    df.groupby(["cat_id", "date"])["sales"]
    .transform(lambda x: x.shift(1).rolling(7).mean())
)

# downcast new features to save memory
for col in df.select_dtypes(include=["float64"]).columns:
    df[col] = df[col].astype("float32")

# drop intermediate price lag column to save memory
df = df.drop(columns=["price_lag_1"])

# drop unnecessary columns (used to create better features, not needed anymore)
df = df.drop(columns=[ "wm_yr_wk", "weekday", "year"])

print(df.shape)

C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f"lag_{lag}"] = df.groupby(["store_id", "item_id"])["sales"].shift(lag)
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f"lag_{lag}"] = df.groupby(["store_id", "item_id"])["sales"].shift(lag)
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df[f"lag_{lag}"] = df.groupby(["store_id", "item_id"])["sales"].shift(lag)
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:13: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = df.groupby(["store_id", "item_id"])["sales"]
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:27: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df["price_lag_1"] = df.groupby(["store_id", "item_id"])["sell_price"].shift(1)
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:32: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["store_id", "item_id"])["sell_price"]
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:52: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["store_id", "date"])["sales"]
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\1697551663.py:58: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["cat_id", "date"])["sales"]

(13537560, 26)

In [6]:
# using all data:
# 30,490 item-store series × 1,913 days ≈ 58,356,370 rows

# using last 500 days only:
# 30,490 item-store series × 500 days = 15,245,000 rows

In [7]:
df.columns

Index(['id', 'item_id', 'dept_id', 'cat_id', 'store_id', 'state_id', 'sales',
       'date', 'wday', 'month', 'sell_price', 'snap', 'event_type', 'lag_1',
       'lag_7', 'lag_28', 'rmean_3', 'rmean_7', 'rmean_28', 'price_change',
       'price_mean_7', 'dayofweek', 'weekofyear', 'is_weekend',
       'store_sales_mean_7', 'cat_sales_mean_7'],
      dtype='object')

### time based train val split

In [8]:
# cutoff 
cutoff = df["date"].max() - pd.Timedelta(days=28)

train_df = df[df["date"] <= cutoff]
val_df   = df[df["date"] > cutoff]

### modelling

In [9]:
# drop target + identifiers you don’t want as features
drop_cols = ["sales", "date", "id"]

features = [c for c in df.columns if c not in drop_cols]
target = "sales"

In [10]:
# item level model, without tweedie objective, didnt perform well

# model = LGBMRegressor(
#     metric="rmse",
#     n_estimators=1000,
#     learning_rate=0.05,
#     num_leaves=255,
#     subsample=0.8,
#     colsample_bytree=0.8
# )

# cat_cols = [c for c in features if c in df.select_dtypes(include=["category"]).columns]
# model.fit(
#     train_df[features],
#     train_df[target],
#     eval_set=[(val_df[features], val_df[target])],
#     eval_metric="rmse",
#     categorical_feature=cat_cols,
#     callbacks=[
#         lgb.early_stopping(50),
#         lgb.log_evaluation(100)
#     ]
# )

In [11]:
# train a model for each store separately, use tweedie objective - better handling of sparse series 

models = {}

cat_cols_model = [c for c in features if c in df.select_dtypes(include=["category"]).columns]

for store in train_df["store_id"].unique():
    
    print(f"Training store: {store}")
    
    train_store = train_df[train_df["store_id"] == store]
    val_store   = val_df[val_df["store_id"] == store]
    
    model = LGBMRegressor(
        objective="tweedie",
        tweedie_variance_power=1.1,
        n_estimators=1000,
        learning_rate=0.05,
        num_leaves=255,
        subsample=0.8,
        colsample_bytree=0.8
    )
    
    model.fit(
        train_store[features],
        train_store[target],
        eval_set=[(val_store[features], val_store[target])],
        eval_metric="rmse",
        categorical_feature=cat_cols_model,
        callbacks=[
            lgb.early_stopping(50),
            lgb.log_evaluation(100)
        ]
    )
    
    models[store] = model

Training store: CA_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.047775 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4825
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.369731
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 2.01111	valid_0's tweedie: 14.9038
Early stopping, best iteration is:
[80]	valid_0's rmse: 2.00896	valid_0's tweedie: 14.9033
Training store: CA_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.075994 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4729
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.155733
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.84564	valid_0's tweedie: 14.7681
Early stopping, best iteration is:
[68]	valid_0's rmse: 1.84586	valid_0's tweedie: 14.763
Training store: CA_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.054884 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5280
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.722466
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 2.42687	valid_0's tweedie: 19.8638
Early stopping, best iteration is:
[84]	valid_0's rmse: 2.42501	valid_0's tweedie: 19.8632
Training store: CA_4
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.106295 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4395
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score -0.226362
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.3331	valid_0's tweedie: 9.25944
Early stopping, best iteration is:
[73]	valid_0's rmse: 1.33348	valid_0's tweedie: 9.25814
Training store: TX_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.080962 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4824
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.038818
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.58905	valid_0's tweedie: 10.9777
Early stopping, best iteration is:
[74]	valid_0's rmse: 1.58872	valid_0's tweedie: 10.977
Training store: TX_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.068602 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5061
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.225472
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.684	valid_0's tweedie: 12.8702
Early stopping, best iteration is:
[67]	valid_0's rmse: 1.68172	valid_0's tweedie: 12.8702
Training store: TX_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074882 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4957
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.203390
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.67668	valid_0's tweedie: 12.4878
Early stopping, best iteration is:
[66]	valid_0's rmse: 1.67062	valid_0's tweedie: 12.4869
Training store: WI_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.057348 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4546
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.153907
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.5918	valid_0's tweedie: 12.8641
Early stopping, best iteration is:
[76]	valid_0's rmse: 1.59045	valid_0's tweedie: 12.8633
Training store: WI_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.110679 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4907
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.349472
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 2.52667	valid_0's tweedie: 16.8703
Early stopping, best iteration is:
[81]	valid_0's rmse: 2.53405	valid_0's tweedie: 16.8696
Training store: WI_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.133696 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4871
[LightGBM] [Info] Number of data points in the train set: 1268384, number of used features: 21
[LightGBM] [Info] Start training from score 0.113654
Training until validation scores don't improve for 50 rounds
[100]	valid_0's rmse: 1.82139	valid_0's tweedie: 12.9251
Early stopping, best iteration is:
[74]	valid_0's rmse: 1.82812	valid_0's tweedie: 12.9226

### generate predicitons

In [12]:
# retrain on full train data
models = {}

cat_cols_model = [c for c in features if c in df.select_dtypes(include=["category"]).columns]

for store in df["store_id"].unique():
    
    print(f"Retraining store on full data: {store}")
    
    train_store = df[df["store_id"] == store]
    
    model = LGBMRegressor(
        objective="tweedie",
        tweedie_variance_power=1.1,
        n_estimators=80, # average across stores in validation run 
        learning_rate=0.05,
        num_leaves=255,
        subsample=0.8,
        colsample_bytree=0.8
    )
    
    model.fit(
        train_store[features],
        train_store[target],
        categorical_feature=cat_cols_model
    )
    
    models[store] = model

Retraining store on full data: CA_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.056512 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4835
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.371970
Retraining store on full data: CA_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.057798 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4747
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.171583
Retraining store on full data: CA_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.052304 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5283
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.722877
Retraining store on full data: CA_4
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.167068 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4401
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score -0.220695
Retraining store on full data: TX_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074109 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4832
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.041674
Retraining store on full data: TX_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.105508 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 5055
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.227323
Retraining store on full data: TX_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.166577 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4972
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.204471
Retraining store on full data: WI_1
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.111017 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4570
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.158775
Retraining store on full data: WI_2
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.161756 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4901
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.364963
Retraining store on full data: WI_3
[LightGBM] [Warning] Categorical features with more bins than the configured maximum bin number found.
[LightGBM] [Warning] For categorical features, max_bin and max_bin_by_feature may be ignored with a large number of categories.
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.114929 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 4873
[LightGBM] [Info] Number of data points in the train set: 1353756, number of used features: 21
[LightGBM] [Info] Start training from score 0.124254

In [13]:
# RECURSIVE PREDICTION

# last date
last_date = df["date"].max()
future_dates = pd.date_range(last_date + pd.Timedelta(days=1), periods=28)

# base ids
base = df[["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]].drop_duplicates()

# future frame
future_df = base.merge(pd.DataFrame({"date": future_dates}), how="cross")

# merge calendar + prices
future_df = future_df.merge(calendar, on="date", how="left")
future_df = future_df.merge(sell_prices, on=["store_id", "item_id", "wm_yr_wk"], how="left")

# combine with history
full_df = pd.concat([df, future_df], ignore_index=True)
full_df = full_df.sort_values(["store_id", "item_id", "date"])

full_df["sales"] = full_df["sales"].astype("float64")

# -------- FIX: categorical alignment (only valid cols) --------
cat_cols_model = [c for c in features if c in df.select_dtypes(include=["category"]).columns]

for col in cat_cols_model:
    if col in full_df.columns:
        full_df[col] = full_df[col].astype("category")
        full_df[col] = full_df[col].cat.set_categories(df[col].cat.categories)

# -------- RECURSIVE LOOP --------
preds = []

for day in future_dates:
    
    g = full_df.groupby(["store_id", "item_id"])
    
    # --- lag features ---
    full_df["lag_1"] = g["sales"].shift(1)
    full_df["lag_7"] = g["sales"].shift(7)
    full_df["lag_28"] = g["sales"].shift(28)
    
    # --- rolling ---
    full_df["rmean_7"] = g["sales"].shift(1).rolling(7).mean()
    full_df["rmean_28"] = g["sales"].shift(1).rolling(28).mean()
    
    # --- calendar features ---
    full_df["dayofweek"] = full_df["date"].dt.dayofweek
    full_df["month"] = full_df["date"].dt.month
    full_df["is_weekend"] = (full_df["dayofweek"] >= 5).astype(int)
    
    # --- price features ---
    full_df["price_lag_1"] = g["sell_price"].shift(1)
    full_df["price_change"] = full_df["sell_price"] / full_df["price_lag_1"]
    full_df["price_change"] = full_df["price_change"].replace([np.inf, -np.inf], 1).fillna(1)
    
    # --- select current day ---
    mask = full_df["date"] == day
    X = full_df.loc[mask, features]
    
    # --- store-wise prediction ---
    y_pred = np.zeros(len(X))
    
    for store in X["store_id"].unique():
        mask_store = X["store_id"] == store
        y_pred[mask_store] = models[store].predict(X.loc[mask_store])
    
    # write back for recursion
    full_df.loc[mask, "sales"] = y_pred
    
    preds.append(y_pred)

# final predictions
preds = np.stack(preds, axis=1)

print(preds.shape)  # should be (30490, 28)

C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:18: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  full_df = pd.concat([df, future_df], ignore_index=True)
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])
C:\Users\Ariel\AppData\Local\Temp\ipykernel_16248\2357839104.py:36: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  g = full_df.groupby(["store_id", "item_id"])

(30490, 28)

### generating submission file for base line model eval

In [14]:
# load sample submission for structure
sample_sub = pd.read_csv("sample_submission.csv")

# FIX: remove existing suffix to get base ids
base_ids = sales["id"].str.replace("_validation", "", regex=False)

# create prediction df
preds_df = pd.DataFrame(preds, columns=[f"F{i}" for i in range(1, 29)])
preds_df["id"] = base_ids.values

# build validation + evaluation ids correctly
preds_val = preds_df.copy()
preds_val["id"] = preds_val["id"] + "_validation"

preds_eval = preds_df.copy()
preds_eval["id"] = preds_eval["id"] + "_evaluation"

# combine
submission = pd.concat([preds_val, preds_eval], axis=0)

# reorder to match sample submission
submission = submission.set_index("id").loc[sample_sub["id"]].reset_index()

# save
submission.to_csv("submission2.csv", index=False)

# sanity check
print(submission.shape)  # should be (60980, 29)

(60980, 29)

### hyperparameter tuning

In [15]:
# ideally we'd like to use hyperparameter tuning with validation set and use wmrsse to select best model, but memory issues prevent that for now. We can do that later if we have time.

In [16]:
# use wrmsse for hyperparam tuning

# Feature Testing Section (Added)

This section tests new feature groups on top of the existing model.

Run cells below **after the original notebook builds `df`**.

In [37]:
from m5_feature_ablation_memorylean import (
    add_candidate_features,
    BASELINE_FEATURES,
    CANDIDATE_GROUPS,
    run_feature_ablation
)

In [38]:
# create dataframe with new candidate features
df2 = add_candidate_features(df.copy())

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[93]	valid_0's rmse: 2.02083	valid_0's tweedie: 14.9169
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[131]	valid_0's rmse: 1.85484	valid_0's tweedie: 14.7694
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[300]	valid_0's rmse: 2.43607	valid_0's tweedie: 19.8683
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[114]	valid_0's rmse: 1.34262	valid_0's tweedie: 9.26947
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[254]	valid_0's rmse: 1.5837	valid_0's tweedie: 10.9825
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[73]	valid_0's rmse: 1.70085	valid_0's tweedie: 12.8808
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[75]	valid_0's rmse: 1.68385	valid_0's tweedie: 12.4963
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[149]	valid_0's rmse: 1.59907	valid_0's tweedie: 12.8722
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[125]	valid_0's rmse: 2.5827	valid_0's tweedie: 16.8827
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[178]	valid_0's rmse: 1.83892	valid_0's tweedie: 12.9325

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,intermittency,27,0.756907,-0.001106,"days_since_last_sale, nonzero_count_7, nonzero..."
1,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."

## Test 1 — Intermittency Features
This tests:
- days_since_last_sale
- nonzero_count_7
- nonzero_count_28
- zero_ratio_28
- recently_active_7
- recently_active_28

In [ ]:
results_intermit = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups={"intermittency": CANDIDATE_GROUPS["intermittency"]},
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_intermit
# See the results above

## Test 2 — Price Features

In [39]:
results_price = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups={"price": CANDIDATE_GROUPS["price_depth"]},
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_price

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[76]	valid_0's rmse: 2.02302	valid_0's tweedie: 14.9192
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[62]	valid_0's rmse: 1.8634	valid_0's tweedie: 14.7722
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[111]	valid_0's rmse: 2.44788	valid_0's tweedie: 19.8704
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[72]	valid_0's rmse: 1.34495	valid_0's tweedie: 9.27038
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[68]	valid_0's rmse: 1.59318	valid_0's tweedie: 10.988
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 1.70282	valid_0's tweedie: 12.8811
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 1.68111	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[59]	valid_0's rmse: 1.61137	valid_0's tweedie: 12.8799
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[107]	valid_0's rmse: 2.56492	valid_0's tweedie: 16.8829
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[114]	valid_0's rmse: 1.86072	valid_0's tweedie: 12.9353

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."
1,price,26,0.760081,0.002068,"price_vs_mean, price_vs_max, discount_depth, w..."

## Test 3 — Hierarchy Features

In [40]:
results_hier = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups={"hierarchy": CANDIDATE_GROUPS["hierarchy"]},
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_hier

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 2.01056	valid_0's tweedie: 14.91
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[140]	valid_0's rmse: 1.84967	valid_0's tweedie: 14.7631
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[192]	valid_0's rmse: 2.43541	valid_0's tweedie: 19.8646
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 1.34	valid_0's tweedie: 9.26302
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[98]	valid_0's rmse: 1.58532	valid_0's tweedie: 10.9801
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[97]	valid_0's rmse: 1.69535	valid_0's tweedie: 12.871
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[67]	valid_0's rmse: 1.68033	valid_0's tweedie: 12.4928
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60008	valid_0's tweedie: 12.869
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[120]	valid_0's rmse: 2.57361	valid_0's tweedie: 16.8768
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[289]	valid_0's rmse: 1.83458	valid_0's tweedie: 12.923

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,hierarchy,25,0.755319,-0.002695,"store_dept_mean_7, store_cat_mean_7, state_cat..."
1,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."

## Test 4 — Same weekday features

In [41]:
results_dow = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups={"dow": CANDIDATE_GROUPS["same_weekday"]},
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_dow

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[116]	valid_0's rmse: 2.01923	valid_0's tweedie: 14.9148
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[270]	valid_0's rmse: 1.83778	valid_0's tweedie: 14.7651
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[119]	valid_0's rmse: 2.44129	valid_0's tweedie: 19.8705
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[132]	valid_0's rmse: 1.34025	valid_0's tweedie: 9.26825
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[84]	valid_0's rmse: 1.58572	valid_0's tweedie: 10.9854
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[64]	valid_0's rmse: 1.69436	valid_0's tweedie: 12.8808
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[65]	valid_0's rmse: 1.6825	valid_0's tweedie: 12.4974
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[135]	valid_0's rmse: 1.59231	valid_0's tweedie: 12.8714
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[145]	valid_0's rmse: 2.58435	valid_0's tweedie: 16.8815
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[122]	valid_0's rmse: 1.84233	valid_0's tweedie: 12.9317

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,dow,24,0.756987,-0.001026,"same_dow_mean_4w, same_dow_mean_8w, same_dow_m..."
1,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."

In [42]:
combo_groups = {
    "hierarchy_plus_intermittency": (
        CANDIDATE_GROUPS["hierarchy"] + CANDIDATE_GROUPS["intermittency"]
    )
}

results_combo = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups=combo_groups,
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_combo

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[163]	valid_0's rmse: 2.00797	valid_0's tweedie: 14.9064
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[145]	valid_0's rmse: 1.85093	valid_0's tweedie: 14.7623
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[220]	valid_0's rmse: 2.4374	valid_0's tweedie: 19.8632
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[82]	valid_0's rmse: 1.33858	valid_0's tweedie: 9.26289
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 1.58271	valid_0's tweedie: 10.9778
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 1.69318	valid_0's tweedie: 12.8733
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[79]	valid_0's rmse: 1.6819	valid_0's tweedie: 12.4904
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[146]	valid_0's rmse: 1.60207	valid_0's tweedie: 12.8686
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[137]	valid_0's rmse: 2.57866	valid_0's tweedie: 16.8759
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[263]	valid_0's rmse: 1.83021	valid_0's tweedie: 12.9224

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,hierarchy_plus_intermittency,31,0.754181,-0.003832,"store_dept_mean_7, store_cat_mean_7, state_cat..."
1,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."

In [43]:
combo_groups = {
    "hierarchy_only": CANDIDATE_GROUPS["hierarchy"],
    "hierarchy_plus_intermittency": (
        CANDIDATE_GROUPS["hierarchy"]
        + CANDIDATE_GROUPS["intermittency"]
    ),
    "hierarchy_plus_dow": (
        CANDIDATE_GROUPS["hierarchy"]
        + CANDIDATE_GROUPS["same_weekday"]
    ),
    "hierarchy_plus_intermit_plus_dow": (
        CANDIDATE_GROUPS["hierarchy"]
        + CANDIDATE_GROUPS["intermittency"]
        + CANDIDATE_GROUPS["same_weekday"]
    ),
}

results_combo = run_feature_ablation(
    df=df2,
    base_features=BASELINE_FEATURES,
    candidate_groups=combo_groups,
    target_col="sales",
    date_col="date",
    store_col="store_id",
)

results_combo

Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 2.02374	valid_0's tweedie: 14.9194
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[127]	valid_0's rmse: 1.84925	valid_0's tweedie: 14.7695
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[298]	valid_0's rmse: 2.43733	valid_0's tweedie: 19.8692
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[104]	valid_0's rmse: 1.34427	valid_0's tweedie: 9.27073
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[129]	valid_0's rmse: 1.58779	valid_0's tweedie: 10.9863
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[69]	valid_0's rmse: 1.70139	valid_0's tweedie: 12.8821
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.68502	valid_0's tweedie: 12.4973
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60212	valid_0's tweedie: 12.8737
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 2.56681	valid_0's tweedie: 16.8826
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[169]	valid_0's rmse: 1.84507	valid_0's tweedie: 12.9336
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 2.01056	valid_0's tweedie: 14.91
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[140]	valid_0's rmse: 1.84967	valid_0's tweedie: 14.7631
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[192]	valid_0's rmse: 2.43541	valid_0's tweedie: 19.8646
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[91]	valid_0's rmse: 1.34	valid_0's tweedie: 9.26302
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[98]	valid_0's rmse: 1.58532	valid_0's tweedie: 10.9801
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[97]	valid_0's rmse: 1.69535	valid_0's tweedie: 12.871
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[67]	valid_0's rmse: 1.68033	valid_0's tweedie: 12.4928
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[171]	valid_0's rmse: 1.60008	valid_0's tweedie: 12.869
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[120]	valid_0's rmse: 2.57361	valid_0's tweedie: 16.8768
Training until validation scores don't improve for 30 rounds
Did not meet early stopping. Best iteration is:
[289]	valid_0's rmse: 1.83458	valid_0's tweedie: 12.923
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[163]	valid_0's rmse: 2.00797	valid_0's tweedie: 14.9064
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[145]	valid_0's rmse: 1.85093	valid_0's tweedie: 14.7623
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[220]	valid_0's rmse: 2.4374	valid_0's tweedie: 19.8632
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[82]	valid_0's rmse: 1.33858	valid_0's tweedie: 9.26289
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[134]	valid_0's rmse: 1.58271	valid_0's tweedie: 10.9778
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[70]	valid_0's rmse: 1.69318	valid_0's tweedie: 12.8733
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[79]	valid_0's rmse: 1.6819	valid_0's tweedie: 12.4904
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[146]	valid_0's rmse: 1.60207	valid_0's tweedie: 12.8686
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[137]	valid_0's rmse: 2.57866	valid_0's tweedie: 16.8759
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[263]	valid_0's rmse: 1.83021	valid_0's tweedie: 12.9224
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[108]	valid_0's rmse: 2.01241	valid_0's tweedie: 14.9069
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[178]	valid_0's rmse: 1.83878	valid_0's tweedie: 14.7602
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[111]	valid_0's rmse: 2.43674	valid_0's tweedie: 19.865
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[78]	valid_0's rmse: 1.33638	valid_0's tweedie: 9.26128
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[115]	valid_0's rmse: 1.58279	valid_0's tweedie: 10.9782
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[61]	valid_0's rmse: 1.68953	valid_0's tweedie: 12.875
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[71]	valid_0's rmse: 1.68006	valid_0's tweedie: 12.4908
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[113]	valid_0's rmse: 1.59942	valid_0's tweedie: 12.8683
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[119]	valid_0's rmse: 2.58772	valid_0's tweedie: 16.8754
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[267]	valid_0's rmse: 1.8249	valid_0's tweedie: 12.9217
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[90]	valid_0's rmse: 2.00898	valid_0's tweedie: 14.9074
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[90]	valid_0's rmse: 1.84563	valid_0's tweedie: 14.7617
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[103]	valid_0's rmse: 2.43821	valid_0's tweedie: 19.8644
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[79]	valid_0's rmse: 1.33439	valid_0's tweedie: 9.26092
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[94]	valid_0's rmse: 1.5862	valid_0's tweedie: 10.9782
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[64]	valid_0's rmse: 1.68764	valid_0's tweedie: 12.8732
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[65]	valid_0's rmse: 1.68041	valid_0's tweedie: 12.4914
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[181]	valid_0's rmse: 1.59063	valid_0's tweedie: 12.8653
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[123]	valid_0's rmse: 2.58147	valid_0's tweedie: 16.8771
Training until validation scores don't improve for 30 rounds
Early stopping, best iteration is:
[202]	valid_0's rmse: 1.82501	valid_0's tweedie: 12.9221

,group_name,n_features,local_avg_rmsse,delta_vs_baseline,features_added
0,hierarchy_plus_intermittency,31,0.754181,-0.003832,"store_dept_mean_7, store_cat_mean_7, state_cat..."
1,hierarchy_plus_intermit_plus_dow,34,0.754587,-0.003426,"store_dept_mean_7, store_cat_mean_7, state_cat..."
2,hierarchy_plus_dow,28,0.754866,-0.003148,"store_dept_mean_7, store_cat_mean_7, state_cat..."
3,hierarchy_only,25,0.755319,-0.002695,"store_dept_mean_7, store_cat_mean_7, state_cat..."
4,baseline_only,21,0.758013,0.000000,"item_id, dept_id, cat_id, store_id, state_id, ..."